# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
---
# Generated by furyctl from immutable.yaml — DO NOT EDIT.
# Only the version vars the infrastructure apply.yaml roles (containerd, haproxy) read.
containerd_sandbox_image: {{ .versions.containerd_sandbox_image }}
haproxy_container_image: {{ .versions.haproxy_container_image }}
haproxy_container_tag: {{ .versions.haproxy_container_tag }}
