# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

name: qa
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: license-check
    image: quay.io/sighup/golang:1.19.6
    commands:
      - make license-check

  - name: schema-check
    image: quay.io/sighup/golang:1.19.6
    commands:
      - |-
        cat schemas/public/ekscluster-kfd-v1alpha2.json | \
        json-patch -p schemas/private/patch.json | \
        jq -r > /tmp/schemas-private-ekscluster-kfd-v1alpha2.json
      - diff schemas/private/ekscluster-kfd-v1alpha2.json /tmp/schemas-private-ekscluster-kfd-v1alpha2.json

  - name: lint
    image: quay.io/sighup/policeman
    pull: always
    environment:
      # Identifies false positives like missing 'selector'.
      # Doing this is valid for Kustomize patches
      VALIDATE_KUBERNETES_KUBEVAL: "false"
      # Some duplicated code is intended.
      VALIDATE_JSCPD: "false"
      # Disable natural language checks
      VALIDATE_NATURAL_LANGUAGE: "false"
      # Disable go linting, we use the one included in the go image
      VALIDATE_GO: "false"
      # Exclude template files from linting. The linter does not understand Go template.
      FILTER_REGEX_EXCLUDE: (templates/distribution/)
    depends_on:
      - license-check
      - schema-check

  - name: lint-go
    image: quay.io/sighup/golang:1.19.6


  - name: render
    # KUBECTL 1.25.3 - KUSTOMIZE 3.5.3 - HELM 3.1.1 - YQ 4.21.1 - ISTIOCTL 1.9.4 - FURYCTL 0.9.0 - BATS 1.1.0
    image: quay.io/sighup/e2e-testing:1.1.0_0.9.0_3.1.1_1.9.4_1.25.3_3.5.3_4.21.1
    pull: always
    commands:
      - echo $${NETRC_FILE} > /root/.netrc
      - furyctl vendor -H
      - kustomize build . > distribution.yml
    environment:
      NETRC_FILE:
        from_secret: NETRC_FILE
    depends_on:
      - license-check
      - schema-check

  - name: check-deprecated-apis
    image: us-docker.pkg.dev/fairwinds-ops/oss/pluto:v5
    pull: always
    depends_on:
      - render
    commands:
      # we use --ignore-deprecations because we don't want the CI to fail when the API has not been removed yet.
      - /pluto detect distribution.yml --ignore-deprecations --target-versions=k8s=v1.25.0

---
name: e2e-kubernetes-1.25
kind: pipeline
type: docker

node:
  runner: internal

depends_on:
  - qa

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**
      - refs/heads/master
      - refs/heads/main
      - refs/heads/release-v**
    exclude:
      - refs/tags/**-docs*

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v1.25.3
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [clone]
    settings:
      action: custom-cluster-125
      pipeline_id: cluster-125
      local_kind_config_path: tests/config/kind-config-custom
      cluster_version: '1.25.3'
      instance_path: /shared
      instance_size: 2-extra-large
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password

  - name: e2e
    # KUBECTL 1.25.3 - KUSTOMIZE 3.5.3 - HELM 3.1.1 - YQ 4.21.1 - ISTIOCTL 1.9.4 - FURYCTL 0.9.0 - BATS 1.1.0
    image: quay.io/sighup/e2e-testing:1.1.0_0.9.0_3.1.1_1.9.4_1.25.3_3.5.3_4.21.1
    pull: always
    volumes:
      - name: shared
        path: /shared
    depends_on: [init]
    commands:
      - ls -la /shared/
      - ls -la /shared/kube/
      - export KUBECONFIG=/shared/kube/kubeconfig-125
      - bats -t tests/install.sh
      - bats -t tests/networking.sh
      - bats -t tests/monitoring.sh
      - bats -t tests/logging.sh
      - bats -t tests/ingress.sh
      - bats -t tests/dr.sh
      - bats -t tests/opa.sh
      - bats -t tests/schema.sh

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v1.25.3
    depends_on: [ test ]
    settings:
      action: destroy
      pipeline_id: cluster-125
      instance_size: 2-extra-large
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
      vsphere_server:
        from_secret: vsphere_server
      vsphere_password:
        from_secret: vsphere_password
      vsphere_user:
        from_secret: vsphere_user
      dockerhub_username:
        from_secret: dockerhub_username
      dockerhub_password:
        from_secret: dockerhub_password
    when:
      status:
        - success
        - failure

volumes:
  - name: shared
    temp: {}

---
name: release
kind: pipeline
type: docker

depends_on:
  - e2e-kubernetes-1.25

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**
    exclude:
      - refs/tags/**-docs*

steps:
  - name: prepare-canonical-json
    image: registry.sighup.io/poc/fury-repo-automations:v0.0.3
    depends_on: [clone]
    commands:
      - spock distro-json -r=False -v=${DRONE_TAG}
    when:
      ref:
        include:
          - refs/tags/**
        exclude:
          - refs/tags/**-docs*

  - name: prepare-release-manifests
    image: quay.io/sighup/e2e-testing:1.1.0_0.7.0_3.1.1_1.9.4_1.24.1_3.8.7_4.21.1
    depends_on: [clone]
    environment:
      RELEASE_MANIFESTS_PATH: fury-distribution-${DRONE_TAG}.yml
    commands:
      - furyctl vendor -H
      - kustomize build . > $${RELEASE_MANIFESTS_PATH}
      - cp tests/config/kind-config-custom kind-config-${DRONE_TAG}.yml
    when:
      ref:
        include:
          - refs/tags/**
        exclude:
          - refs/tags/**-docs*

  - name: prepare-release-notes
    image: quay.io/sighup/fury-release-notes-plugin:3.7_2.8.4
    depends_on: [clone]
    settings:
      release_notes_file_path: release-notes.md
    when:
      ref:
        include:
          - refs/tags/**
        exclude:
          - refs/tags/**-docs*

  - name: publish-prerelease
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-canonical-json
      - prepare-release-manifests
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: skip
      files:
        - fury-distribution-${DRONE_TAG}.yml
        - kind-config-${DRONE_TAG}.yml
        - Furyfile.yml
        - kustomization.yaml
        - kfd-canonical-definition-${DRONE_TAG}.json
      prerelease: true
      overwrite: true
      title: "Prerelease ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        include:
          - refs/tags/v**-rc**
        exclude:
          - refs/tags/**-docs*

  - name: publish-stable
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-canonical-json
      - prepare-release-manifests
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: skip
      files:
        - fury-distribution-${DRONE_TAG}.yml
        - kind-config-${DRONE_TAG}.yml
        - Furyfile.yml
        - kustomization.yaml
        - kfd-canonical-definition-${DRONE_TAG}.json
      prerelease: false
      overwrite: true
      title: "Release ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        exclude:
          - refs/tags/v**-rc**
          - refs/tags/**-docs*
        include:
          - refs/tags/v**
