{
 "title": "Kube-burner report - aggregated",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "uuid",
    "label": "UUID",
    "query": "{\"find\": \"terms\", \"field\": \"uuid.keyword\"}"
   },
   {
    "name": "master",
    "label": "Master nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\", \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: master AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.namespace.keyword\", \"query\": \"uuid.keyword: $uuid\"}"
   },
   {
    "name": "verb",
    "label": "Verb",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.verb.keyword\",  \"query\": \"metricName.keyword: API99thLatency AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "resource",
    "label": "Resource",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.resource.keyword\",  \"query\": \"metricName.keyword: API99thLatency AND uuid.keyword: $uuid\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Job Summary",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:409",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"jobSummary\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4404",
       "fake": true,
       "field": "labels.role.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeRoles\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Final pod status summary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4404",
       "fake": true,
       "field": "labels.phase.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"podStatusCount\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Secrets",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"secretCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "ConfigMaps",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"configmapCount\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Kubernetes version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"clusterVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "versi",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"etcdVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Namespaces",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"namespaceCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Services",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"serviceCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Deployments",
     "bucketAggs": [
      {
       "$$hashKey": "object:1116",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1114",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"deploymentCount\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Monitoring stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:182",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4367",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: containerCPU-Prometheus",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Prometheus RSS Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:182",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4367",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: containerMemory-Prometheus",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "etcd 99th disk WAL fsync latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {
          "script": "params._source['value'] != null ? params._source['value'] : 0.0"
         },
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"99thEtcdDiskWalFsyncDurationSeconds\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "etcd 99th disk backend commit latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {
          "script": "params._source['value'] != null ? params._source['value'] : 0.0"
         },
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"99thEtcdDiskBackendCommitDurationSeconds\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Etcd leader",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 245 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Etcd leader changes",
       "bucketAggs": [
        {
         "$$hashKey": "object:280",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:278",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: etcdLeaderChangesRate",
       "timeField": "timestamp"
      },
      {
       "alias": "Current leader: {{term labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:375",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:280",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:278",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: etcdServerIsLeader",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Etcd object count rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 245 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "{{term labels.resource.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:280",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:278",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: etcdObjectCount",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Etcd DB size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "Physical size: {{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:322",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:259",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:278",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: etcdDBPhysicalSizeBytes",
       "timeField": "timestamp"
      },
      {
       "alias": "Logical size: {{labels.pod.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:337",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:280",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:278",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: etcdDBLogicalSizeBytes",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Etcd 99th network peer roundtrip time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}} to {{labels.To.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:806",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:322",
         "fake": true,
         "field": "labels.To.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:259",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:278",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {
          "script": "params._source['value'] != null ? params._source['value'] : 0.0"
         },
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: 99thEtcdRoundTripTimeSeconds",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Node status summary",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 261 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.condition.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeStatus\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Pod status summary",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 261 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4404",
         "fake": true,
         "field": "labels.phase.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"podStatusCount\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "API P99 latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 269 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:4367",
         "fake": true,
         "field": "labels.verb.keyword",
         "id": "3",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {
          "script": "params._source['value'] != null ? params._source['value'] : 0.0"
         },
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: API99thLatency",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "API request P99 latency",
     "type": "timeseries",
     "description": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\", verb!~\"WATCH\", subresource!=\"log\"}[2m])) by (verb,resource,subresource,instance,le)) > 0",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "{{labels.verb.keyword}} {{labels.resource.keyword}}",
       "bucketAggs": [
        {
         "field": "labels.verb.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "labels.resource.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "value",
         "id": "1",
         "settings": {
          "script": "params._source['value'] != null ? params._source['value'] : 0.0"
         },
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: API99thLatency AND labels.verb.keyword: $verb AND labels.resource.keyword: $resource",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "API request rate",
     "type": "timeseries",
     "description": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\", verb!~\"WATCH\", subresource!=\"log\"}[2m])) by (verb,resource,subresource,instance,le)) > 0",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "{{labels.verb.keyword}} {{labels.resource.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:122",
         "fake": true,
         "field": "labels.verb.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:169",
         "fake": true,
         "field": "labels.resource.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {
          "script": "params._source['value'] != null ? params._source['value'] : 0.0"
         },
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: APIRequestRate AND labels.verb.keyword: $verb AND labels.resource.keyword: $resource",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "API inflight requests",
     "type": "timeseries",
     "description": "sum(apiserver_current_inflight_requests{}) by (request_kind) > 0",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 245 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "{{labels.request_kind.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:122",
         "fake": true,
         "field": "labels.request_kind.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:4301",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:4299",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName.keyword: APIInflightRequests",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Pod latency stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Average pod latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:80",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:78",
       "field": "podReadyLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:139",
       "field": "schedulingLatency",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:119",
       "field": "initializedLatency",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: podLatencyMeasurement",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Pod latencies summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "{{field}} {{term quantileName.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:485",
       "fake": true,
       "field": "quantileName.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:342",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:340",
       "field": "P99",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: podLatencyQuantilesMeasurement",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Golang stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Go heap allocated and inuse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.job.keyword}}: {{labels.instance.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1186",
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:909",
       "fake": true,
       "field": "labels.job.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:817",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:815",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: goHeapAllocBytes",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Go heap inuse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.job.keyword}}: {{labels.instance.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1257",
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:909",
       "fake": true,
       "field": "labels.job.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:817",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:815",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: goHeapInuseBytes",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Go gc duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "{{labels.job.keyword}}: {{labels.instance.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1092",
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:909",
       "fake": true,
       "field": "labels.job.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:817",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:815",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {
        "script": "params._source['value'] != null ? params._source['value'] : 0.0"
       },
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName.keyword: goGCDurationSeconds",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Cluster Kubelet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Aggregated Kubelet CPU usage in nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Kubelet CPU usage - workers",
     "bucketAggs": [
      {
       "$$hashKey": "object:61",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:59",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {
        "script": "params._source['value'] != null ? params._source['value'] : 0.0"
       },
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: \"KubeletCPU-AggregatedWorkers\"",
     "timeField": "timestamp"
    },
    {
     "alias": "CRI-O CPU usage - workers",
     "bucketAggs": [
      {
       "$$hashKey": "object:61",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:59",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: \"CrioCPU-AggregatedWorkers\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Aggregated control plane metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "Aggregated CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Aggregated {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-Masters\" AND labels.namespace.keyword: kube-system",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Aggregated Memory RSS usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Aggregated {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-Masters\" AND labels.namespace.keyword: kube-system",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Individual CPU usage: kube-controller-manager",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}:  {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:256",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-Masters\" AND labels.container.keyword: kube-controller-manager",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Individual Memory RSS: kube-controller-manager",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}:  {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:256",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-Masters\" AND labels.container.keyword: kube-controller-manager",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Master: $master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "repeat": "master",
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage $master",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1106 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}: {{labels.container.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:107",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:307",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-Masters\" AND labels.node.keyword: $master AND labels.namespace.keyword: $namespace",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Container memory usage $master",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1106 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "{{labels.pod.keyword}}: {{labels.container.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:139",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-Masters\" AND labels.node.keyword: $master AND labels.namespace.keyword: $namespace",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Container disk write rate: $master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1117 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "{{labels.container.keyword}}: {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:236",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:221",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerDiskUsage\" AND labels.node.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Memory $master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1117 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "available",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryAvailable-Masters\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      },
      {
       "alias": "cached+buffers",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryCached+nodeMemoryBuffers-Masters\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      },
      {
       "alias": "active",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryActive-Masters\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU $master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1126 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "{{labels.mode.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:133",
         "fake": true,
         "field": "labels.mode.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": "_value*100",
         "meta": {},
         "settings": { "script": { "inline": "_value*100" } },
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeCPU-Masters\" AND labels.instance.keyword: $master",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Disk $master",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1126 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "Written bytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:554",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1089",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1087",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"nodeDiskWrittenBytes-Masters\" AND labels.instance.keyword: \"$master\"",
       "timeField": "timestamp"
      },
      {
       "alias": "Read bytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:571",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1195",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1193",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND  metricName: \"nodeDiskReadBytes-Masters\" AND labels.instance.keyword: \"$master\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Network bytes $master",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1161 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "txNetworkBytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1174",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1089",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1087",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"txNetworkBytes-Masters\" AND labels.instance.keyword: \"$master\"",
       "timeField": "timestamp"
      },
      {
       "alias": "rxNetworkBytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1215",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1195",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1193",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND  metricName: \"rxNetworkBytes-Masters\" AND labels.instance.keyword: \"$master\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Worker nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Avg. container CPU usage in worker nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {
        "script": "params._source['value'] != null ? params._source['value'] : 0.0"
       },
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-AggregatedWorkers\" AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Avg. container memory usage in worker nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-AggregatedWorkers\"  AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Worker nodes Avg CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.mode.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:133",
       "fake": true,
       "field": "labels.mode.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": "_value*100",
       "meta": {},
       "settings": { "script": { "inline": "_value*100" } },
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeCPU-AggregatedWorkers\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Worker nodes Avg memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "available",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryAvailable-AggregatedWorkers\"",
     "timeField": "timestamp"
    },
    {
     "alias": "cached+buffers",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryCached+nodeMemoryBuffers-AggregatedWorkers\"",
     "timeField": "timestamp"
    },
    {
     "alias": "available",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryActive-AggregatedWorkers\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Worker nodes avg. network bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "txNetworkBytes - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1174",
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1089",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1087",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"txNetworkBytes-AggregatedWorkers\"",
     "timeField": "timestamp"
    },
    {
     "alias": "rxNetworkBytes - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1215",
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1195",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1193",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND  metricName: \"rxNetworkBytes-AggregatedWorkers\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Worker nodes disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Written bytes - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:554",
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1089",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1087",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"nodeDiskWrittenBytes-AggregatedWorkers\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Read bytes - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:571",
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1195",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1193",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND  metricName: \"nodeDiskReadBytes-AggregatedWorkers\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Infrastructure nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Avg. container CPU usage in infra nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-AggregatedInfra\" AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Avg. container memory usage in infra nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:159",
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-AggregatedInfra\"  AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Infra nodes Avg CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{labels.mode.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:133",
       "fake": true,
       "field": "labels.mode.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": "_value*100",
       "meta": {},
       "settings": { "script": { "inline": "_value*100" } },
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeCPU-AggregatedInfra\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Infra nodes Avg memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "available",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryAvailable-AggregatedInfra\"",
     "timeField": "timestamp"
    },
    {
     "alias": "cached+buffers",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryCached+nodeMemoryBuffers-AggregatedInfra\"",
     "timeField": "timestamp"
    },
    {
     "alias": "available",
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryActive-AggregatedInfra\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Infra nodes avg. network bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "txNetworkBytes - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1174",
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1089",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1087",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"txNetworkBytes-AggregatedInfra\"",
     "timeField": "timestamp"
    },
    {
     "alias": "rxNetworkBytes - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1215",
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1195",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1193",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND  metricName: \"rxNetworkBytes-AggregatedInfra\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Infra nodes disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Written bytes - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:554",
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1089",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1087",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"nodeDiskWrittenBytes-AggregatedInfra\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Read bytes - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:571",
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1195",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1193",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND  metricName: \"nodeDiskReadBytes-AggregatedInfra\"",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}