# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
---
# Generated by furyctl from immutable.yaml — DO NOT EDIT.
kubernetes_version: {{ .versions.kubernetes_version }}
kubernetes_image_registry: {{ .versions.kubernetes_image_registry }}
containerd_sandbox_image: {{ .versions.containerd_sandbox_image }}
coredns_image_prefix: {{ .versions.coredns_image_prefix }}
haproxy_container_image: {{ .versions.haproxy_container_image }}
haproxy_container_tag: {{ .versions.haproxy_container_tag }}
kubelet_csr_approver_tag: {{ .versions.kubelet_csr_approver_tag }}
os_update_target_version: {{ .versions.os_update_target_version }}
{{- if .versions.kubectl_bin }}
kubectl_bin: {{ .versions.kubectl_bin }}
{{- end }}
sysext_targets:
{{- range $name, $t := .versions.sysext_targets }}
  {{ $name }}:
    version: {{ $t.version }}
    arch:
{{- range $arch, $a := $t.arch }}
      {{ $arch }}:
        url: {{ $a.url }}
{{- end }}
{{- end }}
