// Code generated by github.com/sighupio/go-jsonschema, DO NOT EDIT.

package public

import "encoding/json"
import "fmt"
import "reflect"

// A KFD Cluster deployed on Flatcar Container Linux using the Immutable provider
// with Matchbox-based provisioning.
type ImmutableKfdV1Alpha2 struct {
	// ApiVersion corresponds to the JSON schema field "apiVersion".
	ApiVersion string `json:"apiVersion" yaml:"apiVersion" mapstructure:"apiVersion"`

	// Kind corresponds to the JSON schema field "kind".
	Kind ImmutableKfdV1Alpha2Kind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Metadata corresponds to the JSON schema field "metadata".
	Metadata Metadata `json:"metadata" yaml:"metadata" mapstructure:"metadata"`

	// Spec corresponds to the JSON schema field "spec".
	Spec Spec `json:"spec" yaml:"spec" mapstructure:"spec"`
}

type ImmutableKfdV1Alpha2Kind string

const ImmutableKfdV1Alpha2KindImmutable ImmutableKfdV1Alpha2Kind = "Immutable"

type Metadata struct {
	// The name of the cluster. It will also be used as a prefix for all the other
	// resources created.
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

type Spec struct {
	// Distribution corresponds to the JSON schema field "distribution".
	Distribution *SpecDistribution `json:"distribution,omitempty" yaml:"distribution,omitempty" mapstructure:"distribution,omitempty"`

	// Defines which KFD version will be installed and, in consequence, the Kubernetes
	// version used to create the cluster. It supports git tags and branches. Example:
	// `v1.33.1`.
	DistributionVersion string `json:"distributionVersion" yaml:"distributionVersion" mapstructure:"distributionVersion"`

	// Infrastructure corresponds to the JSON schema field "infrastructure".
	Infrastructure SpecInfrastructure `json:"infrastructure" yaml:"infrastructure" mapstructure:"infrastructure"`

	// Kubernetes corresponds to the JSON schema field "kubernetes".
	Kubernetes SpecKubernetes `json:"kubernetes" yaml:"kubernetes" mapstructure:"kubernetes"`

	// Plugins corresponds to the JSON schema field "plugins".
	Plugins *SpecPlugins `json:"plugins,omitempty" yaml:"plugins,omitempty" mapstructure:"plugins,omitempty"`
}

// SIGHUP Distribution modules configuration. This section is compatible with the
// existing Distribution schema and follows the same structure as other providers.
type SpecDistribution struct {
	// Common corresponds to the JSON schema field "common".
	Common *SpecDistributionCommon `json:"common,omitempty" yaml:"common,omitempty" mapstructure:"common,omitempty"`

	// Distribution modules (networking, ingress, logging, monitoring, dr, policy,
	// etc.). Follows the standard SIGHUP Distribution modules schema.
	Modules SpecDistributionModules `json:"modules,omitempty" yaml:"modules,omitempty" mapstructure:"modules,omitempty"`
}

type SpecDistributionCommon struct {
	// Container registry for Distribution modules. Example: registry.sighup.io/fury
	Registry *string `json:"registry,omitempty" yaml:"registry,omitempty" mapstructure:"registry,omitempty"`
}

// Distribution modules (networking, ingress, logging, monitoring, dr, policy,
// etc.). Follows the standard SIGHUP Distribution modules schema.
type SpecDistributionModules map[string]interface{}

// Defines the infrastructure layer configuration for the Immutable provider. This
// section defines infrastructure concerns (Matchbox, OS updates, PKI, SSH access,
// node inventory) separate from Kubernetes concerns.
type SpecInfrastructure struct {
	// Matchbox corresponds to the JSON schema field "matchbox".
	Matchbox SpecInfrastructureMatchbox `json:"matchbox" yaml:"matchbox" mapstructure:"matchbox"`

	// Nodes corresponds to the JSON schema field "nodes".
	Nodes SpecInfrastructureNodes `json:"nodes" yaml:"nodes" mapstructure:"nodes"`

	// OsUpdates corresponds to the JSON schema field "osUpdates".
	OsUpdates *SpecInfrastructureOSUpdates `json:"osUpdates,omitempty" yaml:"osUpdates,omitempty" mapstructure:"osUpdates,omitempty"`

	// Pki corresponds to the JSON schema field "pki".
	Pki *SpecInfrastructurePKI `json:"pki,omitempty" yaml:"pki,omitempty" mapstructure:"pki,omitempty"`

	// Ssh corresponds to the JSON schema field "ssh".
	Ssh SpecInfrastructureSSH `json:"ssh" yaml:"ssh" mapstructure:"ssh"`
}

// Matchbox server configuration for PXE/iPXE provisioning.
type SpecInfrastructureMatchbox struct {
	// Internal HTTPS URL that target nodes will contact during PXE boot. Must be
	// accessible from all nodes during boot. Must resolve to the Matchbox server IP
	// (can be furyctl serve matchbox or remote Matchbox). Example:
	// https://matchbox.internal.example.com:8080
	Url TypesUri `json:"url" yaml:"url" mapstructure:"url"`
}

// Network interface configuration for a node.
type SpecInfrastructureNetworkInterface struct {
	// IP addresses in CIDR notation. Required if dhcp is false. Example:
	// ['10.0.1.10/24']
	Addresses []TypesCidr `json:"addresses,omitempty" yaml:"addresses,omitempty" mapstructure:"addresses,omitempty"`

	// Use DHCP (true) or static IP configuration (false).
	Dhcp bool `json:"dhcp" yaml:"dhcp" mapstructure:"dhcp"`

	// DNS server IP addresses. Optional. Example: ['10.0.1.53', '1.1.1.1']
	Dns []TypesIpAddress `json:"dns,omitempty" yaml:"dns,omitempty" mapstructure:"dns,omitempty"`

	// Default gateway IP address. Required if dhcp is false.
	Gateway *TypesIpAddress `json:"gateway,omitempty" yaml:"gateway,omitempty" mapstructure:"gateway,omitempty"`

	// Interface name. Examples: eno1, ens3, eth0
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// Node definition with network configuration. Applies to all roles: controlPlanes,
// workers, etcds, loadBalancers.
type SpecInfrastructureNode struct {
	// FQDN hostname. Applied by Ignition at first boot. Must be a fully qualified
	// domain name. Example: master1.prod.example.com
	Hostname TypesFqdn `json:"hostname" yaml:"hostname" mapstructure:"hostname"`

	// Disk device for Flatcar Container Linux installation. Example: /dev/sda,
	// /dev/nvme0n1
	InstallDisk string `json:"installDisk" yaml:"installDisk" mapstructure:"installDisk"`

	// Primary MAC address. Used by Matchbox for group selection and node-to-profile
	// mapping. Format: 52:54:00:aa:bb:01
	MacAddress TypesMacAddress `json:"macAddress" yaml:"macAddress" mapstructure:"macAddress"`

	// Network interface configuration. At least one interface is required.
	NetworkInterfaces []SpecInfrastructureNetworkInterface `json:"networkInterfaces" yaml:"networkInterfaces" mapstructure:"networkInterfaces"`

	// Partitioning strategy. Default: auto
	Partitioning SpecInfrastructureNodePartitioning `json:"partitioning,omitempty" yaml:"partitioning,omitempty" mapstructure:"partitioning,omitempty"`
}

type SpecInfrastructureNodePartitioning string

const SpecInfrastructureNodePartitioningAuto SpecInfrastructureNodePartitioning = "auto"

// Node inventory organized by role. Supported roles: controlPlanes (Kubernetes
// control-plane with stacked etcd by default), workers (Kubernetes worker nodes),
// loadBalancers (HAProxy load balancers), etcds (optional dedicated etcd nodes,
// triggers external etcd).
type SpecInfrastructureNodes struct {
	// Kubernetes control-plane nodes. By default, etcd runs stacked on these nodes
	// unless dedicated etcd nodes are specified.
	ControlPlanes []SpecInfrastructureNode `json:"controlPlanes" yaml:"controlPlanes" mapstructure:"controlPlanes"`

	// Optional dedicated etcd nodes. If provided, triggers external etcd
	// configuration. If omitted, etcd runs stacked on control-plane nodes.
	Etcds []SpecInfrastructureNode `json:"etcds,omitempty" yaml:"etcds,omitempty" mapstructure:"etcds,omitempty"`

	// HAProxy load balancer nodes with keepalived for high availability. Optional. If
	// omitted, clients connect directly to control plane.
	LoadBalancers []SpecInfrastructureNode `json:"loadBalancers,omitempty" yaml:"loadBalancers,omitempty" mapstructure:"loadBalancers,omitempty"`

	// Kubernetes worker nodes. Run workload pods.
	Workers []SpecInfrastructureNode `json:"workers" yaml:"workers" mapstructure:"workers"`
}

// Controls how Flatcar Container Linux nodes receive OS updates via Nebraska
// (Omaha protocol).
type SpecInfrastructureOSUpdates struct {
	// Allow OS updates to run during 'furyctl apply' cluster updates. If enabled, OS
	// updates can occur while cluster components are being updated. Default: false
	AllowDuringClusterUpdate bool `json:"allowDuringClusterUpdate,omitempty" yaml:"allowDuringClusterUpdate,omitempty" mapstructure:"allowDuringClusterUpdate,omitempty"`

	// Enable OS update management. Default: true
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Nebraska server endpoint for OS updates. If omitted, uses SIGHUP-managed
	// Nebraska server. Provide custom URL for your own Nebraska server (e.g.,
	// https://nebraska.internal.example.com). Examples: 'default' (SIGHUP-managed),
	// custom URL
	Server *string `json:"server,omitempty" yaml:"server,omitempty" mapstructure:"server,omitempty"`

	// Update strategy. 'manual': updates require approval. 'automatic': updates apply
	// automatically during cluster maintenance. Default: manual
	UpdateStrategy SpecInfrastructureOSUpdatesUpdateStrategy `json:"updateStrategy,omitempty" yaml:"updateStrategy,omitempty" mapstructure:"updateStrategy,omitempty"`
}

type SpecInfrastructureOSUpdatesUpdateStrategy string

const SpecInfrastructureOSUpdatesUpdateStrategyAutomatic SpecInfrastructureOSUpdatesUpdateStrategy = "automatic"
const SpecInfrastructureOSUpdatesUpdateStrategyManual SpecInfrastructureOSUpdatesUpdateStrategy = "manual"

// PKI (Public Key Infrastructure) configuration for certificates.
type SpecInfrastructurePKI struct {
	// Path to folder containing certificates generated by 'furyctl generate pki'.
	// Default: ./pki
	Folder string `json:"folder,omitempty" yaml:"folder,omitempty" mapstructure:"folder,omitempty"`
}

// SSH configuration for accessing cluster nodes.
type SpecInfrastructureSSH struct {
	// Path to SSH private key for authentication. Example: ~/.ssh/id_ed25519_cluster
	KeyPath string `json:"keyPath" yaml:"keyPath" mapstructure:"keyPath"`

	// SSH port on target nodes. Default: 22
	Port TypesTcpPort `json:"port,omitempty" yaml:"port,omitempty" mapstructure:"port,omitempty"`

	// SSH user with sudo NOPASSWD access. Default: core (Flatcar default user)
	Username string `json:"username,omitempty" yaml:"username,omitempty" mapstructure:"username,omitempty"`
}

// Kubernetes cluster configuration for Ansible. References nodes from
// spec.infrastructure.nodes with hostname and management IP (must be one of the
// IPs from networkInterfaces).
type SpecKubernetes struct {
	// Advanced corresponds to the JSON schema field "advanced".
	Advanced *SpecKubernetesAdvanced `json:"advanced,omitempty" yaml:"advanced,omitempty" mapstructure:"advanced,omitempty"`

	// FQDN or IP address for the Kubernetes API Server endpoint. Points to the load
	// balancer VIP (if using HAProxy) or a single control-plane node. Example:
	// k8s-api.prod.example.com
	ControlPlaneAddress string `json:"controlPlaneAddress" yaml:"controlPlaneAddress" mapstructure:"controlPlaneAddress"`

	// API server port. Default: 6443
	ControlPlanePort TypesTcpPort `json:"controlPlanePort,omitempty" yaml:"controlPlanePort,omitempty" mapstructure:"controlPlanePort,omitempty"`

	// Control plane nodes for Ansible configuration. Must reference nodes from
	// spec.infrastructure.nodes.controlPlanes.
	ControlPlanes []SpecKubernetesNode `json:"controlPlanes" yaml:"controlPlanes" mapstructure:"controlPlanes"`

	// External etcd nodes for Ansible configuration. Must reference nodes from
	// spec.infrastructure.nodes.etcds.
	Etcds []SpecKubernetesNode `json:"etcds,omitempty" yaml:"etcds,omitempty" mapstructure:"etcds,omitempty"`

	// LoadBalancers corresponds to the JSON schema field "loadBalancers".
	LoadBalancers *SpecKubernetesLoadBalancers `json:"loadBalancers,omitempty" yaml:"loadBalancers,omitempty" mapstructure:"loadBalancers,omitempty"`

	// Networking corresponds to the JSON schema field "networking".
	Networking *SpecKubernetesNetworking `json:"networking,omitempty" yaml:"networking,omitempty" mapstructure:"networking,omitempty"`

	// Worker nodes for Ansible configuration. Must reference nodes from
	// spec.infrastructure.nodes.workers.
	Workers []SpecKubernetesNode `json:"workers" yaml:"workers" mapstructure:"workers"`
}

// Advanced Kubernetes configuration options. Most fields use sensible defaults and
// only need to be specified if you need to override them.
type SpecKubernetesAdvanced struct {
	// ApiServer corresponds to the JSON schema field "apiServer".
	ApiServer *SpecKubernetesAdvancedAPIServer `json:"apiServer,omitempty" yaml:"apiServer,omitempty" mapstructure:"apiServer,omitempty"`

	// Container registry for Kubernetes components. Example: registry.sighup.io/fury
	Registry *string `json:"registry,omitempty" yaml:"registry,omitempty" mapstructure:"registry,omitempty"`
}

// Kubernetes API Server advanced configuration.
type SpecKubernetesAdvancedAPIServer struct {
	// Extra arguments to pass to the API server. Key-value pairs. Example:
	// {'audit-log-path': '/var/log/kubernetes/audit.log'}
	ExtraArgs SpecKubernetesAdvancedAPIServerExtraArgs `json:"extraArgs,omitempty" yaml:"extraArgs,omitempty" mapstructure:"extraArgs,omitempty"`
}

// Extra arguments to pass to the API server. Key-value pairs. Example:
// {'audit-log-path': '/var/log/kubernetes/audit.log'}
type SpecKubernetesAdvancedAPIServerExtraArgs map[string]string

// Load balancer host reference for Ansible configuration. Hostname must match a
// node from spec.infrastructure.nodes.loadBalancers, and IP must be one of the IPs
// from that node's networkInterfaces.
type SpecKubernetesLoadBalancerHost struct {
	// FQDN hostname of the load balancer. Must match one of the hostnames from
	// spec.infrastructure.nodes.loadBalancers. Example: lb1.prod.example.com
	Hostname TypesFqdn `json:"hostname" yaml:"hostname" mapstructure:"hostname"`

	// Management IP address for Ansible configuration. Must be one of the IPs
	// configured in the corresponding node's networkInterfaces in
	// spec.infrastructure.nodes.
	Ip TypesIpAddress `json:"ip" yaml:"ip" mapstructure:"ip"`
}

// HAProxy load balancers with keepalived for high availability. If disabled,
// cluster can use external load balancer or direct DNS to a control plane node.
type SpecKubernetesLoadBalancers struct {
	// Enable HAProxy load balancers. If false, controlPlaneAddress must point to an
	// external load balancer or directly to a control plane node. Default: false
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Load balancer host nodes. Required when enabled is true. Each must reference a
	// node from spec.infrastructure.nodes.loadBalancers.
	Hosts []SpecKubernetesLoadBalancerHost `json:"hosts,omitempty" yaml:"hosts,omitempty" mapstructure:"hosts,omitempty"`

	// Vrrp corresponds to the JSON schema field "vrrp".
	Vrrp *SpecKubernetesVRRP `json:"vrrp,omitempty" yaml:"vrrp,omitempty" mapstructure:"vrrp,omitempty"`
}

// Kubernetes network configuration.
type SpecKubernetesNetworking struct {
	// The subnet CIDR to use for the Pods network. Default: 10.244.0.0/16
	PodCIDR TypesCidr `json:"podCIDR,omitempty" yaml:"podCIDR,omitempty" mapstructure:"podCIDR,omitempty"`

	// The subnet CIDR to use for the Services network. Must not overlap with podCIDR.
	// Default: 10.96.0.0/12
	ServiceCIDR TypesCidr `json:"serviceCIDR,omitempty" yaml:"serviceCIDR,omitempty" mapstructure:"serviceCIDR,omitempty"`
}

// Kubernetes node reference for Ansible configuration. Hostname must match a node
// from spec.infrastructure.nodes, and IP must be one of the IPs from that node's
// networkInterfaces.
type SpecKubernetesNode struct {
	// FQDN hostname. Must match one of the hostnames from spec.infrastructure.nodes.
	// Example: master1.prod.example.com
	Hostname TypesFqdn `json:"hostname" yaml:"hostname" mapstructure:"hostname"`

	// Management IP address for Ansible configuration. Must be one of the IPs
	// configured in the corresponding node's networkInterfaces in
	// spec.infrastructure.nodes.
	Ip TypesIpAddress `json:"ip" yaml:"ip" mapstructure:"ip"`
}

// VRRP (Virtual Router Redundancy Protocol) configuration for keepalived. If
// disabled, load balancers work without high availability (single active LB).
type SpecKubernetesVRRP struct {
	// Password for VRRP authentication. Required when enabled is true. Prevents rogue
	// VRRP instances. Best practice: use environment variable substitution (e.g.,
	// $VRRP_PASSWORD). Maximum length: 8 characters
	AuthPassword *string `json:"authPassword,omitempty" yaml:"authPassword,omitempty" mapstructure:"authPassword,omitempty"`

	// Enable VRRP for load balancer high availability. If false, only the first load
	// balancer will be active. Default: false
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Network interface where the VIP will be configured. Required when enabled is
	// true. Must exist on ALL load balancer nodes. Examples: ens3, eth0, eno1
	Interface *string `json:"interface,omitempty" yaml:"interface,omitempty" mapstructure:"interface,omitempty"`

	// Virtual IP (VIP) shared between load balancers in CIDR format. Required when
	// enabled is true. Must be in the same subnet as load balancer nodes. Must NOT be
	// assigned to any physical interface. Must be the IP that controlPlaneAddress
	// resolves to. Example: 10.0.1.100/24
	VirtualIP *TypesCidr `json:"virtualIP,omitempty" yaml:"virtualIP,omitempty" mapstructure:"virtualIP,omitempty"`

	// Unique identifier for the VRRP router. Required when enabled is true. Must be
	// unique in the network segment. Range: 1-255
	VirtualRouterID *int `json:"virtualRouterID,omitempty" yaml:"virtualRouterID,omitempty" mapstructure:"virtualRouterID,omitempty"`
}

type SpecPlugins struct {
	// Helm corresponds to the JSON schema field "helm".
	Helm *SpecPluginsHelm `json:"helm,omitempty" yaml:"helm,omitempty" mapstructure:"helm,omitempty"`

	// Kustomize corresponds to the JSON schema field "kustomize".
	Kustomize SpecPluginsKustomize `json:"kustomize,omitempty" yaml:"kustomize,omitempty" mapstructure:"kustomize,omitempty"`
}

type SpecPluginsHelm struct {
	// Releases corresponds to the JSON schema field "releases".
	Releases SpecPluginsHelmReleases `json:"releases,omitempty" yaml:"releases,omitempty" mapstructure:"releases,omitempty"`

	// Repositories corresponds to the JSON schema field "repositories".
	Repositories SpecPluginsHelmRepositories `json:"repositories,omitempty" yaml:"repositories,omitempty" mapstructure:"repositories,omitempty"`
}

type SpecPluginsHelmReleases []struct {
	// The chart of the release
	Chart string `json:"chart" yaml:"chart" mapstructure:"chart"`

	// Disable running `helm diff` validation when installing the plugin, it will
	// still be done when upgrading.
	DisableValidationOnInstall *bool `json:"disableValidationOnInstall,omitempty" yaml:"disableValidationOnInstall,omitempty" mapstructure:"disableValidationOnInstall,omitempty"`

	// The name of the release
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// The namespace of the release
	Namespace string `json:"namespace" yaml:"namespace" mapstructure:"namespace"`

	// Set corresponds to the JSON schema field "set".
	Set []SpecPluginsHelmReleasesElemSetElem `json:"set,omitempty" yaml:"set,omitempty" mapstructure:"set,omitempty"`

	// The values of the release
	Values []string `json:"values,omitempty" yaml:"values,omitempty" mapstructure:"values,omitempty"`

	// The version of the release
	Version *string `json:"version,omitempty" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

type SpecPluginsHelmReleasesElemSetElem struct {
	// The name of the set
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// The value of the set
	Value string `json:"value" yaml:"value" mapstructure:"value"`
}

type SpecPluginsHelmRepositories []struct {
	// The name of the repository
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// The url of the repository
	Url string `json:"url" yaml:"url" mapstructure:"url"`
}

type SpecPluginsKustomize []struct {
	// The folder of the kustomize plugin
	Folder string `json:"folder" yaml:"folder" mapstructure:"folder"`

	// The name of the kustomize plugin. A lowercase RFC 1123 subdomain must consist
	// of lower case alphanumeric characters, '-' or '.', and must start and end with
	// an alphanumeric character (e.g. 'example.com', 'local-storage')
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// IPv4 CIDR notation (IP address with subnet mask /0-32). Example: 192.168.1.0/24
type TypesCidr string

// Fully Qualified Domain Name (FQDN). Must include domain suffix. Example:
// server.example.com
type TypesFqdn string

// IPv4 address in dotted decimal notation (0.0.0.0 to 255.255.255.255). Example:
// 192.168.1.100
type TypesIpAddress string

// MAC address in colon-separated hexadecimal format. Example: 52:54:00:12:34:56
type TypesMacAddress string

// TCP/UDP port number (1-65535)
type TypesTcpPort int

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecKubernetesNode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["hostname"]; !ok || v == nil {
		return fmt.Errorf("field hostname in SpecKubernetesNode: required")
	}
	if v, ok := raw["ip"]; !ok || v == nil {
		return fmt.Errorf("field ip in SpecKubernetesNode: required")
	}
	type Plain SpecKubernetesNode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = SpecKubernetesNode(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecKubernetesLoadBalancerHost) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["hostname"]; !ok || v == nil {
		return fmt.Errorf("field hostname in SpecKubernetesLoadBalancerHost: required")
	}
	if v, ok := raw["ip"]; !ok || v == nil {
		return fmt.Errorf("field ip in SpecKubernetesLoadBalancerHost: required")
	}
	type Plain SpecKubernetesLoadBalancerHost
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = SpecKubernetesLoadBalancerHost(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecInfrastructure) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["matchbox"]; !ok || v == nil {
		return fmt.Errorf("field matchbox in SpecInfrastructure: required")
	}
	if v, ok := raw["nodes"]; !ok || v == nil {
		return fmt.Errorf("field nodes in SpecInfrastructure: required")
	}
	if v, ok := raw["ssh"]; !ok || v == nil {
		return fmt.Errorf("field ssh in SpecInfrastructure: required")
	}
	type Plain SpecInfrastructure
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = SpecInfrastructure(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecKubernetesVRRP) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	type Plain SpecKubernetesVRRP
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if plain.AuthPassword != nil && len(*plain.AuthPassword) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "authPassword", 1)
	}
	if plain.AuthPassword != nil && len(*plain.AuthPassword) > 8 {
		return fmt.Errorf("field %s length: must be <= %d", "authPassword", 8)
	}
	if v, ok := raw["enabled"]; !ok || v == nil {
		plain.Enabled = false
	}
	if plain.Interface != nil && len(*plain.Interface) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "interface", 1)
	}
	*j = SpecKubernetesVRRP(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecInfrastructureSSH) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["keyPath"]; !ok || v == nil {
		return fmt.Errorf("field keyPath in SpecInfrastructureSSH: required")
	}
	type Plain SpecInfrastructureSSH
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if len(plain.KeyPath) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "keyPath", 1)
	}
	if v, ok := raw["port"]; !ok || v == nil {
		plain.Port = 22.0
	}
	if v, ok := raw["username"]; !ok || v == nil {
		plain.Username = "core"
	}
	if len(plain.Username) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "username", 1)
	}
	*j = SpecInfrastructureSSH(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecKubernetesLoadBalancers) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	type Plain SpecKubernetesLoadBalancers
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if v, ok := raw["enabled"]; !ok || v == nil {
		plain.Enabled = false
	}
	if plain.Hosts != nil && len(plain.Hosts) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "hosts", 1)
	}
	*j = SpecKubernetesLoadBalancers(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecInfrastructurePKI) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	type Plain SpecInfrastructurePKI
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if v, ok := raw["folder"]; !ok || v == nil {
		plain.Folder = "./pki"
	}
	*j = SpecInfrastructurePKI(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecKubernetesNetworking) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	type Plain SpecKubernetesNetworking
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if v, ok := raw["podCIDR"]; !ok || v == nil {
		plain.PodCIDR = "10.244.0.0/16"
	}
	if v, ok := raw["serviceCIDR"]; !ok || v == nil {
		plain.ServiceCIDR = "10.96.0.0/12"
	}
	*j = SpecKubernetesNetworking(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecInfrastructureOSUpdates) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	type Plain SpecInfrastructureOSUpdates
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowDuringClusterUpdate"]; !ok || v == nil {
		plain.AllowDuringClusterUpdate = false
	}
	if v, ok := raw["enabled"]; !ok || v == nil {
		plain.Enabled = true
	}
	if plain.Server != nil && len(*plain.Server) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "server", 1)
	}
	if v, ok := raw["updateStrategy"]; !ok || v == nil {
		plain.UpdateStrategy = "manual"
	}
	*j = SpecInfrastructureOSUpdates(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecKubernetes) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["controlPlaneAddress"]; !ok || v == nil {
		return fmt.Errorf("field controlPlaneAddress in SpecKubernetes: required")
	}
	if v, ok := raw["controlPlanes"]; !ok || v == nil {
		return fmt.Errorf("field controlPlanes in SpecKubernetes: required")
	}
	if v, ok := raw["workers"]; !ok || v == nil {
		return fmt.Errorf("field workers in SpecKubernetes: required")
	}
	type Plain SpecKubernetes
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if len(plain.ControlPlaneAddress) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "controlPlaneAddress", 1)
	}
	if v, ok := raw["controlPlanePort"]; !ok || v == nil {
		plain.ControlPlanePort = 6443.0
	}
	if plain.ControlPlanes != nil && len(plain.ControlPlanes) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "controlPlanes", 1)
	}
	if plain.Etcds != nil && len(plain.Etcds) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "etcds", 1)
	}
	if plain.Workers != nil && len(plain.Workers) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "workers", 1)
	}
	*j = SpecKubernetes(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecInfrastructureOSUpdatesUpdateStrategy) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SpecInfrastructureOSUpdatesUpdateStrategy {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SpecInfrastructureOSUpdatesUpdateStrategy, v)
	}
	*j = SpecInfrastructureOSUpdatesUpdateStrategy(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecPluginsHelmReleasesElemSetElem) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["name"]; !ok || v == nil {
		return fmt.Errorf("field name in SpecPluginsHelmReleasesElemSetElem: required")
	}
	if v, ok := raw["value"]; !ok || v == nil {
		return fmt.Errorf("field value in SpecPluginsHelmReleasesElemSetElem: required")
	}
	type Plain SpecPluginsHelmReleasesElemSetElem
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = SpecPluginsHelmReleasesElemSetElem(plain)
	return nil
}

var enumValues_SpecInfrastructureOSUpdatesUpdateStrategy = []interface{}{
	"manual",
	"automatic",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecInfrastructureNodes) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["controlPlanes"]; !ok || v == nil {
		return fmt.Errorf("field controlPlanes in SpecInfrastructureNodes: required")
	}
	if v, ok := raw["workers"]; !ok || v == nil {
		return fmt.Errorf("field workers in SpecInfrastructureNodes: required")
	}
	type Plain SpecInfrastructureNodes
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if plain.ControlPlanes != nil && len(plain.ControlPlanes) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "controlPlanes", 1)
	}
	if plain.Etcds != nil && len(plain.Etcds) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "etcds", 1)
	}
	if plain.LoadBalancers != nil && len(plain.LoadBalancers) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "loadBalancers", 1)
	}
	if plain.Workers != nil && len(plain.Workers) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "workers", 1)
	}
	*j = SpecInfrastructureNodes(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecInfrastructureNode) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["hostname"]; !ok || v == nil {
		return fmt.Errorf("field hostname in SpecInfrastructureNode: required")
	}
	if v, ok := raw["installDisk"]; !ok || v == nil {
		return fmt.Errorf("field installDisk in SpecInfrastructureNode: required")
	}
	if v, ok := raw["macAddress"]; !ok || v == nil {
		return fmt.Errorf("field macAddress in SpecInfrastructureNode: required")
	}
	if v, ok := raw["networkInterfaces"]; !ok || v == nil {
		return fmt.Errorf("field networkInterfaces in SpecInfrastructureNode: required")
	}
	type Plain SpecInfrastructureNode
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if len(plain.InstallDisk) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "installDisk", 1)
	}
	if plain.NetworkInterfaces != nil && len(plain.NetworkInterfaces) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "networkInterfaces", 1)
	}
	if v, ok := raw["partitioning"]; !ok || v == nil {
		plain.Partitioning = "auto"
	}
	*j = SpecInfrastructureNode(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecInfrastructureNodePartitioning) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SpecInfrastructureNodePartitioning {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SpecInfrastructureNodePartitioning, v)
	}
	*j = SpecInfrastructureNodePartitioning(v)
	return nil
}

var enumValues_SpecInfrastructureNodePartitioning = []interface{}{
	"auto",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecInfrastructureNetworkInterface) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["dhcp"]; !ok || v == nil {
		return fmt.Errorf("field dhcp in SpecInfrastructureNetworkInterface: required")
	}
	if v, ok := raw["name"]; !ok || v == nil {
		return fmt.Errorf("field name in SpecInfrastructureNetworkInterface: required")
	}
	type Plain SpecInfrastructureNetworkInterface
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if plain.Addresses != nil && len(plain.Addresses) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "addresses", 1)
	}
	if len(plain.Name) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	*j = SpecInfrastructureNetworkInterface(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Spec) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["distributionVersion"]; !ok || v == nil {
		return fmt.Errorf("field distributionVersion in Spec: required")
	}
	if v, ok := raw["infrastructure"]; !ok || v == nil {
		return fmt.Errorf("field infrastructure in Spec: required")
	}
	if v, ok := raw["kubernetes"]; !ok || v == nil {
		return fmt.Errorf("field kubernetes in Spec: required")
	}
	type Plain Spec
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if len(plain.DistributionVersion) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "distributionVersion", 1)
	}
	*j = Spec(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecInfrastructureMatchbox) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["url"]; !ok || v == nil {
		return fmt.Errorf("field url in SpecInfrastructureMatchbox: required")
	}
	type Plain SpecInfrastructureMatchbox
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = SpecInfrastructureMatchbox(plain)
	return nil
}

var enumValues_ImmutableKfdV1Alpha2Kind = []interface{}{
	"Immutable",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ImmutableKfdV1Alpha2Kind) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ImmutableKfdV1Alpha2Kind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ImmutableKfdV1Alpha2Kind, v)
	}
	*j = ImmutableKfdV1Alpha2Kind(v)
	return nil
}

// Uniform Resource Identifier (URI). Must be a valid URL with scheme. Example:
// https://example.com:8080
type TypesUri string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Metadata) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["name"]; !ok || v == nil {
		return fmt.Errorf("field name in Metadata: required")
	}
	type Plain Metadata
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if len(plain.Name) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if len(plain.Name) > 56 {
		return fmt.Errorf("field %s length: must be <= %d", "name", 56)
	}
	*j = Metadata(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ImmutableKfdV1Alpha2) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["apiVersion"]; !ok || v == nil {
		return fmt.Errorf("field apiVersion in ImmutableKfdV1Alpha2: required")
	}
	if v, ok := raw["kind"]; !ok || v == nil {
		return fmt.Errorf("field kind in ImmutableKfdV1Alpha2: required")
	}
	if v, ok := raw["metadata"]; !ok || v == nil {
		return fmt.Errorf("field metadata in ImmutableKfdV1Alpha2: required")
	}
	if v, ok := raw["spec"]; !ok || v == nil {
		return fmt.Errorf("field spec in ImmutableKfdV1Alpha2: required")
	}
	type Plain ImmutableKfdV1Alpha2
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ImmutableKfdV1Alpha2(plain)
	return nil
}
